"""Add artifacts table for Story 7-2

Revision ID: 0266a00873cc
Revises: 7bd1d9c753bc
Create Date: 2025-11-16 10:20:33.803237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0266a00873cc'
down_revision: Union[str, Sequence[str], None] = '7bd1d9c753bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('original_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.execution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_id'), 'artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_artifacts_execution_id'), 'artifacts', ['execution_id'], unique=False)
    op.drop_constraint(op.f('fk_executions_worker_id'), 'executions', type_='foreignkey')
    op.drop_index(op.f('idx_heartbeats_last'), table_name='worker_heartbeats')
    op.drop_constraint(op.f('fk_worker_heartbeats_worker_id'), 'worker_heartbeats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_worker_heartbeats_worker_id'), 'worker_heartbeats', 'workers', ['worker_id'], ['worker_id'], ondelete='CASCADE')
    op.create_index(op.f('idx_heartbeats_last'), 'worker_heartbeats', ['last_heartbeat_at'], unique=False)
    op.create_foreign_key(op.f('fk_executions_worker_id'), 'executions', 'workers', ['worker_id'], ['worker_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_artifacts_execution_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
